version: "3"
services:
  db:
    image: postgres:12.4-alpine
    restart: always
    environment:
      POSTGRES_USER: innihald
      POSTGRES_PASSWORD: supersecret
      POSTGRES_DB: innihald
    ports:
      - 5432:5432
    volumes:
      - postgresdb

  pgAdmin:
    image: dpage/pgadmin4:4.25
    environment:
      PGADMIN_DEFAULT_EMAIL: innihald@example.com
      PGADMIN_DEFAULT_PASSWORD: supersecret
    ports:
      - 7010:80

  mongodb:
    image: mongo:4.4.0-bionic
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    ports:
      - 27017:27017

  mongo-express:
    image: mongo-express:0.54.0
    restart: always
    ports:
      - 7020:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_SERVER: mongodb
  
  activemq:
    image: vromero/activemq-artemis:2.15.0-alpine
    restart: always
    ports:
     - 61616:61616
     - 5672:5672
     - 7030:8161
    environment:
      ARTEMIS_USERNAME: root
      ARTEMIS_PASSWORD: example