version: "3"
services:
  db:
    image: postgres:12.4-alpine
    restart: always
    environment:
      POSTGRES_USER: innihald
      POSTGRES_PASSWORD: supersecret
      POSTGRES_DB: innihald
    ports:
      - 5432:5432
    volumes:
      - postgresdb
  pgAdmin:
    image: dpage/pgadmin4:4.25
    environment:
      PGADMIN_DEFAULT_EMAIL: innihald@example.com
      PGADMIN_DEFAULT_PASSWORD: supersecret
    ports:
      - 7010:80